@startuml
!include style.puml

box Model MODEL_COLOR_T1
participant ":MonthlyListMap" as MonthlyListMap MODEL_COLOR
participant ":MonthlyData" as MonthlyData MODEL_COLOR

end box

mainframe **sd** getMonthlyData

box
MonthlyListMap -> MonthlyListMap : getItems(month, year)
activate MonthlyListMap

MonthlyListMap --> MonthlyListMap : list of meetings
deactivate MonthlyListMap
create MonthlyData
MonthlyListMap -> MonthlyData : m, meetings list size
note left: m refers to the MonthAndYear object m \nin the referencing sequence diagrams
activate MonthlyData
MonthlyData --> MonthlyListMap
deactivate MonthlyData

end box

@enduml
