@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR


Class AddressBook
Package Meeting\n <<Rectangle>>{

    Class Meeting
    Class UniqueMeetingList

    AddressBook *--> "    1" UniqueMeetingList
    UniqueMeetingList --> "    *" Meeting
}

Package Person\n {
    Class Person
}

Meeting *--> "  1" Message
Meeting *--> "1" LocalDateTime
Meeting *--> "              1" Duration
Meeting *--> "           1" Person

@enduml
