@startuml
!include style.puml

box Model MODEL_COLOR_T1
participant ":UniqueMeetingList" as UniqueMeetingList MODEL_COLOR
participant ":MonthlyListMap" as MonthlyListMap MODEL_COLOR
participant "m:MonthAndYear" as MonthAndYear MODEL_COLOR
participant ":MonthlyListDataSet" as MonthlyListDataSet MODEL_COLOR

end box

box



UniqueMeetingList -> MonthlyListMap : getMultipleMonthCount(currentMonth, currentYear,  numberOfMonths)
activate MonthlyListMap


create MonthAndYear
MonthlyListMap -> MonthAndYear : currentMonth, currentYear
activate MonthAndYear
MonthAndYear --> MonthlyListMap
deactivate MonthAndYear

ref over MonthlyListMap: getMonthlyData




loop numberOfMonths - 1 times
    ref over MonthlyListMap: getPreviousMonthlyData
end

create MonthlyListDataSet
MonthlyListMap -> MonthlyListDataSet : list of monthlyData
activate MonthlyListDataSet
MonthlyListDataSet --> MonthlyListMap
deactivate MonthlyListDataSet

MonthlyListMap --> UniqueMeetingList : monthlyListDataSet
deactivate MonthlyListMap

@enduml
