@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>> {
    Interface ReadOnlyAddressBook <<Interface>>
    Interface Model <<Interface>>
    Interface ObservableList <<Interface>>
    Class AddressBook
    Class ReadOnlyAddressBook
    Class Model
    Class ModelManager
    Class UserPrefs
    Class ReadOnlyUserPrefs

    Package Person {
        Class Person
        Class Address
        Class Email
        Class Name
        Class Phone
        Class UniquePersonList
    }

    Package Tag {
        Class Tag
    }

    Package Meeting\n {
        Class Meeting
        Class UniqueMeetingList
    }

    Package Reminder\n {
        Class Reminder
        Class UniqueReminderList
    }

    Package Sale {
        Class Sale
        Class ItemName
        Class UnitPrice
        Class Quantity

        Class UniqueSaleList
    }
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" AddressBook
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniquePersonList
UniquePersonList o--> "*" Person
Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> "*" Tag

AddressBook *--> "1" UniqueMeetingList
UniqueMeetingList --> "                    *" Meeting
Meeting *--> "    1" Person
Meeting : Message message
Meeting : LocalDateTime startDate
Meeting : Duration duration

AddressBook *--> "1" UniqueReminderList
UniqueReminderList --> "              *" Reminder
Reminder *--> "   1" Person
Reminder : Message message
Reminder : LocalDateTime scheduledDate

AddressBook *--> "1" UniqueSaleList
UniqueSaleList o--> "*" Sale
Sale *--> ItemName
Sale *--> UnitPrice
Sale *--> Quantity
Sale *--> "1" Person
Sale *--> "*" Tag
Sale : LocalDateTime dateTimeOfPurchase


Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email

ModelManager -->"*" Person : filtered list

show Reminder fields
show Meeting fields
@enduml
