@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class AddressBook

Package Reminder\n <<Rectangle>>{
    Class Reminder
    Class UniqueReminderList
}


AddressBook *--> "     1" UniqueReminderList
UniqueReminderList --> "    *" Reminder

Package Person\n {
    Class Person
}

Reminder *--> "                   1" Person
Reminder *--> "1" Message
Reminder *--> "1" LocalDateTime
Reminder *--> "            1" Completed

@enduml
