@startuml
start
:User keys in command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

:Program parses input;

if () then ([command is in valid format])
    if () then ([index is a positive integer])
        :Create a new Index object;
        if () then ([index does not refer to an existing reminder])
            :Show invalid index warning;
        else ([else])
            :Delete reminder;
            :Show success message;
        endif
    else ([else])
        :Show error message with correct required values;
    endif
else ([else])
    : Show error message with correct command format;
endif

stop
@enduml
