@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant "a:AddCommand" as AddCommand LOGIC_COLOR
participant "<<class>>\n:MassSaleCommandUtil" as MassSaleCommandUtil LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "newSale:Sale" as Sale MODEL_COLOR
participant ":Model" as Model MODEL_COLOR
end box

LogicManager -> AddCommand : execute(model)
activate AddCommand

AddCommand -> Model : getSortedPersonList()
activate Model

Model --> AddCommand
deactivate Model

AddCommand -> MassSaleCommandUtil : arePersonIndexesValid(lastShownList, indexList)
activate MassSaleCommandUtil

MassSaleCommandUtil --> AddCommand
deactivate MassSaleCommandUtil

AddCommand -> Model : saleTagsExist(tagList)
activate Model

Model --> AddCommand
deactivate Model

loop until all specified Sales are processed
    create Sale
    AddCommand -> Sale
    activate Sale

    Sale --> AddCommand : sale
    deactivate Sale

    AddCommand -> Model : hasSale(newSale)
    activate Model

    Model --> AddCommand
    deactivate Model

    opt sale is not a duplicate
        AddCommand -> Model : addSale(newSale)
        activate Model

        Model --> AddCommand
        deactivate Model
    end
end

opt there are duplicate sales
    AddCommand -> AddCommand : generateDuplicateSaleMessage(sales)
    activate AddCommand

    AddCommand -> MassSaleCommandUtil : listAllSales(sales)
    activate MassSaleCommandUtil

    MassSaleCommandUtil --> AddCommand
    deactivate MassSaleCommandUtil

    AddCommand --> AddCommand
    deactivate AddCommand
end

AddCommand -> AddCommand : generateSuccessMessage(sales)
activate AddCommand

AddCommand -> MassSaleCommandUtil : listAllSales(sales)
activate MassSaleCommandUtil

MassSaleCommandUtil --> AddCommand
deactivate MassSaleCommandUtil

AddCommand --> AddCommand
deactivate AddCommand

create CommandResult
AddCommand -> CommandResult
activate CommandResult

CommandResult --> AddCommand
deactivate CommandResult

AddCommand --> LogicManager : result
deactivate AddCommand

'Hidden arrow to position the destroy marker below the end of the activation bar.
AddCommand -[hidden]-> LogicManager
destroy AddCommand

[<--LogicManager
deactivate LogicManager

@enduml
