@startuml
start
:User keys in command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

:Program parses input;

if () then ([command is in valid format])
    if () then ([arguments are valid])
        :Create a new Tag object;
        if () then ([is contact tag])
            if () then ([contact tag already exists])
                :Show duplicate contact tag warning;
            else ([else])
                :Add Tag to contact tags list;
                :Show success message;
            endif
        else ([else])
            if () then ([sales tag already exists])
                :Show duplicate tag warning;
            else ([else])
                :Add Tag to sales tags list;
                :Show success message;
            endif
        endif
    else ([else])
        :Show error message with correct required values;
    endif
else ([else])
    : Show error message with correct command format;
endif

stop
@enduml
