@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":TagCommandsParser" as TagCommandsParser LOGIC_COLOR
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant "<<class>>\nParserUtil" as ParserUtil LOGIC_COLOR
participant "a:AddCommand" as AddCommand LOGIC_COLOR
end box

[-> LogicManager : execute("tag add <args>")
note left: Full command is truncated for brevity
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("tag add <args>")
activate AddressBookParser

create TagCommandsParser
AddressBookParser -> TagCommandsParser
activate TagCommandsParser

TagCommandsParser --> AddressBookParser
deactivate TagCommandsParser

AddressBookParser -> TagCommandsParser : parse("tag add", <args>)
activate TagCommandsParser

create AddCommandParser
TagCommandsParser -> AddCommandParser
activate AddCommandParser

AddCommandParser --> TagCommandsParser
deactivate AddCommandParser

TagCommandsParser -> AddCommandParser : parse(<args>)
activate AddCommandParser

AddCommandParser -> ParserUtil : parseTag(str)
activate ParserUtil

ParserUtil --> AddCommandParser
deactivate ParserUtil

create AddCommand
AddCommandParser -> AddCommand
activate AddCommand

AddCommand --> AddCommandParser : a
deactivate AddCommand

AddCommandParser --> TagCommandsParser : a
deactivate AddCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
AddCommandParser -[hidden]-> TagCommandsParser
destroy AddCommandParser

TagCommandsParser --> AddressBookParser : a
deactivate TagCommandsParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
TagCommandsParser -[hidden]-> AddressBookParser
destroy TagCommandsParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

[<--LogicManager
deactivate LogicManager

@enduml
