@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant "a:AddCommand" as AddCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "newTag:Tag" as Tag MODEL_COLOR
participant ":Model" as Model MODEL_COLOR
end box

LogicManager -> AddCommand : execute(model)
activate AddCommand

alt isContact

    create Tag
    AddCommand -> Tag
    activate Tag

    Tag --> AddCommand
    deactivate Tag

    AddCommand -> Model : hasContactTag(newTag)
    activate Model

    Model --> AddCommand
    deactivate Model

    AddCommand -> Model : addContactTag(newTag)
    activate Model

    Model --> AddCommand
    deactivate Model

else else

    create Tag
    AddCommand -> Tag
    activate Tag

    Tag --> AddCommand
    deactivate Tag

    AddCommand -> Model : hasSaleTag(newTag)
    activate Model

    Model --> AddCommand
    deactivate Model

    AddCommand -> Model : addSaleTag(newTag)
    activate Model

    Model --> AddCommand
    deactivate Model

end

create CommandResult
AddCommand -> CommandResult
activate CommandResult

CommandResult --> AddCommand
deactivate CommandResult

AddCommand --> LogicManager : result
deactivate AddCommand

[<--LogicManager
deactivate LogicManager

@enduml
