@startuml
start
:User keys in command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

:Program parses input;

if () then ([command is in valid format])
    if () then ([arguments are valid])
        :Edit an existing Tag object;
        if () then ([is contact tag])
            :Edit contact tag and update all contacts associated with this tag;
        else ([else])
            :Edit sales tag and update all sales items associated with this tag;
        endif
    else ([else])
        :Show error message with correct required values;
    endif
else ([else])
    : Show error message with correct command format;
endif

stop
@enduml